export default [
  {
    id: 1,
    name: "白沙灣渡假酒店",
    description: "西貢",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 則評語",
    image: require("../../assets/img-house1.jpg"),
  },
  {
    id: 2,
    name: "沙田渡假酒店",
    description: "沙田",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 則評語",
    image: require("../../assets/img-house2.jpg"),
  },
  {
    id: 3,
    name: "馬𩣑山酒店",
    description: "馬𩣑山",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 則評語",
    image: require("../../assets/img-house3.jpg"),
  },
  {
    id: 4,
    name: "白沙灣渡假酒店",
    description: "西貢",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 則評語",
    image: require("../../assets/img-house1.jpg"),
  },
  {
    id: 5,
    name: "沙田渡假酒店",
    description: "沙田",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 則評語",
    image: require("../../assets/img-house2.jpg"),
  },
  {
    id: 6,
    name: "馬𩣑山酒店",
    description: "馬𩣑山",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 則評語",
    image: require("../../assets/img-house3.jpg"),
  },
  {
    id: 7,
    name: "白沙灣渡假酒店",
    description: "西貢",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 則評語",
    image: require("../../assets/img-house1.jpg"),
  },
  {
    id: 8,
    name: "沙田渡假酒店",
    description: "沙田",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 則評語",
    image: require("../../assets/img-house2.jpg"),
  },
  {
    id: 9,
    name: "馬𩣑山酒店",
    description: "馬𩣑山",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 則評語",
    image: require("../../assets/img-house3.jpg"),
  },
  {
    id: 10,
    name: "白沙灣渡假酒店",
    description: "西貢",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 則評語",
    image: require("../../assets/img-house1.jpg"),
  },
  {
    id: 11,
    name: "沙田渡假酒店",
    description: "沙田",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 則評語",
    image: require("../../assets/img-house2.jpg"),
  },
  {
    id: 12,
    name: "馬𩣑山酒店",
    description: "馬𩣑山",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 則評語",
    image: require("../../assets/img-house3.jpg"),
  },
];
