export default [
  {
    id: 1,
    name: "Yummy hamburger",
    description: "Burger",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 points",
  },
  {
    id: 2,
    name: "Yummy hamburger",
    description: "Burger",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 points",
  },
  {
    id: 3,
    name: "Yummy hamburger",
    description: "Burger",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 points",
  },
  {
    id: 4,
    name: "Yummy hamburger",
    description: "Burger",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 points",
  },
  {
    id: 5,
    name: "Yummy hamburger",
    description: "Burger",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 points",
  },
  {
    id: 6,
    name: "Yummy hamburger",
    description: "Burger",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 points",
  },
  {
    id: 7,
    name: "Yummy hamburger",
    description: "Burger",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 points",
  },
  {
    id: 8,
    name: "Yummy hamburger",
    description: "Burger",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 points",
  },
  {
    id: 9,
    name: "Yummy hamburger",
    description: "Burger",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 points",
  },
  {
    id: 10,
    name: "Yummy hamburger",
    description: "Burger",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 points",
  },
  {
    id: 11,
    name: "Yummy hamburger",
    description: "Burger",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 points",
  },
  {
    id: 12,
    name: "Yummy hamburger",
    description: "Burger",
    discount: "HK560",
    price: "HK500",
    rateValue: 4,
    rateText: "62 points",
  },
];
